// Single shared source of job titles, used by complete-profile (onboarding)
// and the profile editor so the list never diverges.
export const TITLES = [
  "Product Manager",
  "Associate Product Manager",
  "Senior Product Manager",
  "Group Product Manager",
  "Principal Product Manager",
  "Director of Product",
  "VP Product",
  "Chief Product Officer",
  "Product Owner",
  "Technical Product Manager",
  "Growth Product Manager",
  "Platform Product Manager",
  "Data Product Manager",
  "AI/ML Product Manager",
  "Product Analyst",
  "Product Marketing Manager",
  "Product Designer",
  "Product Operations",
  "Program Manager",
  "Technical Program Manager",
  "Project Manager",
  "Senior Project Manager",
  "Project Coordinator",
  "Scrum Master",
  "Agile Coach",
  "Delivery Manager",
  "Business Analyst",
  "Other (specify)",
];
